# TESTAR ROTAS 

POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Video #1",
    "duration": 180
}

###

GET http://localhost:3333/videos


###
PUT http://localhost:3333/videos/8a5d0c51-ef35-48a1-952e-a48ca1d1e090"
Content-Type: application/json

{
    "title": "Video 023",
    "description": "Video #2",
    "duration": 180
}

